name: etl-tpch
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dask >=2024.8.0
  - coiled
  - zstandard
  - python-duckdb
  - xgboost
  - fastapi
  - plotly
  - prefect >=2.16
  - filelock
  - streamlit
  - s3fs
  - universal_pathlib <0.2.0
  - boto3
  - deltalake >=0.18
  # - dask-deltatable
  - pip
  - pip:
    - git+https://github.com/dask-contrib/dask-deltatable.git@7706c22aa07f978f481ca4996dce8ca0121c812e
