name: etl-tpch
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dask >=2024.2.0
  - dask-expr
  - coiled
  - zstandard
  - python-duckdb
  - xgboost
  - fastapi
  - plotly
  - prefect
  - filelock
  - streamlit
  - s3fs
  - universal_pathlib
  - boto3
