name: etl-tpch
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dask >=2024.8.0
  - coiled
  - zstandard
  - python-duckdb
  - xgboost
  - fastapi
  - plotly
  - prefect <3
  - filelock
  - streamlit
  - s3fs
  - universal_pathlib <0.2.0
  - boto3
  - deltalake >=0.18
  # - dask-deltatable
  - pip
  - pip:
    - dask-deltatable==0.3.3
