# Output location for data files. Can be a local directory
# or a remote path like "s3://path/to/bucket".
data-dir: ./data-test
# Whether to run data-processing tasks locally
# or on the cloud with Coiled.
local: true
# If using Coiled (`local: false`), use this Coiled workspace.
# Defaults to your default workspace.
workspace: null
